name: Manual Trigger Workflow

on:
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Hello! This workflow was triggered manually."
